name: Build Processor
description: Builds the frc-codex-processor Docker image

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5.3.0
      with:
        cache: 'pip'
        check-latest: true
        python-version: 3.13
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install tox tox-gh-actions
    - name: Test with tox
      shell: bash
      run: tox
    - uses: docker/setup-buildx-action@v3.8.0
    - name: Build frc-codex-processor image
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: frc-codex-processor.Dockerfile
        push: false
        tags: frc-codex-processor
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/frc-codex-processor.tar
